export const movies = [
  {
    adult: false,
    backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
    genre_ids: [10749, 18],
    id: 1010581,
    original_language: 'es',
    original_title: 'Culpa mía',
    overview:
      "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
    popularity: 126.452,
    poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
    release_date: '2023-06-08',
    title: 'My Fault',
    video: false,
    vote_average: 7.832,
    vote_count: 3568,
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 50.933,
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.1,
    vote_count: 5789,
  },
  {
    adult: false,
    backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
    genre_ids: [16, 10751, 12, 14, 35],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 43.275,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-04-05',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 7.6,
    vote_count: 9466,
  },
  {
    adult: false,
    backdrop_path: '/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg',
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: 'en',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview:
      'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
    popularity: 41.394,
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    release_date: '2023-05-31',
    title: 'Spider-Man: Across the Spider-Verse',
    video: false,
    vote_average: 8.3,
    vote_count: 7328,
  },
  {
    adult: false,
    backdrop_path: '/gklkxY0veMajdCiGe6ggsh07VG2.jpg',
    genre_ids: [16, 12, 35, 10751],
    id: 940551,
    original_language: 'en',
    original_title: 'Migration',
    overview:
      'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
    popularity: 39.955,
    poster_path: '/apQL85BMRgkBWQq6pBXKOLfCyaV.jpg',
    release_date: '2023-12-06',
    title: 'Migration',
    video: false,
    vote_average: 7.411,
    vote_count: 1943,
  },
  {
    adult: false,
    backdrop_path: '/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg',
    genre_ids: [18, 36],
    id: 872585,
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 37.244,
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    release_date: '2023-07-19',
    title: 'Oppenheimer',
    video: false,
    vote_average: 8.1,
    vote_count: 9850,
  },
  {
    adult: false,
    backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
    genre_ids: [878, 12, 28],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
    popularity: 36.753,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 7.2,
    vote_count: 4808,
  },
  {
    adult: false,
    backdrop_path: '/7I6VUdPj6tQECNHdviJkUHD2u89.jpg',
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    popularity: 36.117,
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    release_date: '2023-03-22',
    title: 'John Wick: Chapter 4',
    video: false,
    vote_average: 7.7,
    vote_count: 6864,
  },
  {
    adult: false,
    backdrop_path: '/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg',
    genre_ids: [28, 53, 80],
    id: 926393,
    original_language: 'en',
    original_title: 'The Equalizer 3',
    overview:
      "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
    popularity: 34.962,
    poster_path: '/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg',
    release_date: '2023-08-30',
    title: 'The Equalizer 3',
    video: false,
    vote_average: 7.319,
    vote_count: 3152,
  },
  {
    adult: false,
    backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    genre_ids: [878, 12, 28],
    id: 447365,
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 3',
    overview:
      'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    popularity: 32.189,
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    release_date: '2023-05-03',
    title: 'Guardians of the Galaxy Vol. 3',
    video: false,
    vote_average: 7.954,
    vote_count: 7155,
  },
  {
    adult: false,
    backdrop_path: '/3N5QNUqS76GFYNoEayfkkJyAyTN.jpg',
    genre_ids: [35, 12],
    id: 346698,
    original_language: 'en',
    original_title: 'Barbie',
    overview:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    popularity: 31.709,
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    release_date: '2023-07-19',
    title: 'Barbie',
    video: false,
    vote_average: 7,
    vote_count: 9584,
  },
  {
    adult: false,
    backdrop_path: '/oHBhHoNe59VH6bUMazDtJmWOFSS.jpg',
    genre_ids: [878, 27, 28],
    id: 940721,
    original_language: 'ja',
    original_title: 'ゴジラ-1.0',
    overview:
      'In postwar Japan, Godzilla brings new devastation to an already scorched landscape. With no military intervention or government help in sight, the survivors must join together in the face of despair and fight back against an unrelenting horror.',
    popularity: 31.101,
    poster_path: '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
    release_date: '2023-11-03',
    title: 'Godzilla Minus One',
    video: false,
    vote_average: 7.572,
    vote_count: 2527,
  },
  {
    adult: false,
    backdrop_path: '/TFTfzrkX8L7bAKUcch6qLmjpLu.jpg',
    genre_ids: [28, 12],
    id: 575264,
    original_language: 'en',
    original_title: 'Mission: Impossible - Dead Reckoning Part One',
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    popularity: 30.192,
    poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    release_date: '2023-07-08',
    title: 'Mission: Impossible - Dead Reckoning Part One',
    video: false,
    vote_average: 7.5,
    vote_count: 4043,
  },
  {
    adult: false,
    backdrop_path: '/pp3QUzMXfP7q0ocmE1b15FH6PQ6.jpg',
    genre_ids: [28, 35, 10749],
    id: 868759,
    original_language: 'en',
    original_title: 'Ghosted',
    overview:
      "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie—but then makes the shocking discovery that she's a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
    popularity: 29.681,
    poster_path: '/liLN69YgoovHVgmlHJ876PKi5Yi.jpg',
    release_date: '2023-04-18',
    title: 'Ghosted',
    video: false,
    vote_average: 6.9,
    vote_count: 1871,
  },
  {
    adult: false,
    backdrop_path: '/epW5UkPSonOOtZQ39JKrmlSFk8S.jpg',
    genre_ids: [16, 12, 14, 10751, 18],
    id: 508883,
    original_language: 'ja',
    original_title: '君たちはどう生きるか',
    overview:
      'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
    popularity: 26.83,
    poster_path: '/f4oZTcfGrVTXKTWg157AwikXqmP.jpg',
    release_date: '2023-07-14',
    title: 'The Boy and the Heron',
    video: false,
    vote_average: 7.447,
    vote_count: 2030,
  },
  {
    adult: false,
    backdrop_path: '/6YInbRTk39ckuLYFmUgBCKcKNjb.jpg',
    genre_ids: [16, 35, 10751, 14, 10749],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    popularity: 28.395,
    poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 7.6,
    vote_count: 4682,
  },
  {
    adult: false,
    backdrop_path: '/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg',
    genre_ids: [10749, 35],
    id: 1072790,
    original_language: 'en',
    original_title: 'Anyone But You',
    overview:
      'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
    popularity: 27.094,
    poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
    release_date: '2023-12-21',
    title: 'Anyone But You',
    video: false,
    vote_average: 6.897,
    vote_count: 2425,
  },
  {
    adult: false,
    backdrop_path: '/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg',
    genre_ids: [28, 878, 27],
    id: 615656,
    original_language: 'en',
    original_title: 'Meg 2: The Trench',
    overview:
      'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
    popularity: 26.088,
    poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
    release_date: '2023-08-02',
    title: 'Meg 2: The Trench',
    video: false,
    vote_average: 6.5,
    vote_count: 3518,
  },
  {
    adult: false,
    backdrop_path: '/hU1Q9YVzdYhokr8a9gLywnSUMlN.jpg',
    genre_ids: [16, 12, 28, 14, 10751],
    id: 1147400,
    original_language: 'fr',
    original_title:
      'Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire',
    overview:
      "Miraculous holders from another world appear in Paris. They come from a parallel universe where everything is reversed: the holders of Ladybug and Black Cat Miraculouses, Shadybug and Claw Noir, are the bad guys, and the holder of the Butterfly Miraculous, Hesperia, is a superhero. Ladybug and Cat Noir will have to help Hesperia counter the attacks of their evil doubles and prevent them from seizing the Butterfly's Miraculous. Can our heroes also help Hesperia make Shadybug and Claw Noir better people?",
    popularity: 25.446,
    poster_path: '/nydROKumZe9oFZNiSn792MDDA1v.jpg',
    release_date: '2023-10-21',
    title: 'Miraculous World: Paris, Tales of Shadybug and Claw Noir',
    video: false,
    vote_average: 7.2,
    vote_count: 579,
  },
  {
    adult: false,
    backdrop_path: '/55hRgXkbvHoc9dL58S9HAGyxmZt.jpg',
    genre_ids: [27, 53],
    id: 1134433,
    original_language: 'th',
    original_title: 'ธี่หยด',
    overview:
      'When a remote village is plagued by a deadly curse, one brother must fight to save his family from a terrifying supernatural threat.',
    popularity: 24.965,
    poster_path: '/48TDjSJpCdJ4SBOHZX3G5IjaV02.jpg',
    release_date: '2023-10-25',
    title: 'Death Whisperer',
    video: false,
    vote_average: 7.5,
    vote_count: 184,
  },
];

export const genres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
];
